#ifndef RESOURCES_H
#define RESOURCES_H

#define DEFAULT_CLOSE_BUTTON_COLOR TQt::red
#define DEFAULT_MAXIMIZE_BUTTON_COLOR TQt::yellow
#define DEFAULT_ICONIFY_BUTTON_COLOR TQt::green
#define DEFAULT_HELP_BUTTON_COLOR TQt::white
#define DEFAULT_STICKY_BUTTON_COLOR TQt::white

#endif

